@home = File.expand_path("~")
@local_vimrc = File.expand_path("vimrc")
@local_vimdirs = Dir["*"].select{|e| File.directory? e }
@vimrc = File.expand_path("~/.vimrc")
@vim_dir = File.expand_path("~/.vim")
@vimswaps = File.expand_path("~/.vimswaps")

desc "install links for vimrc to ~/.vimrc and vim dirs to ~/.vim"
task :install => :create_folders do
  File.symlink(@local_vimrc, @vimrc)
  @local_vimdirs.each do |dir|
    target = [@vim_dir, dir].join(File::SEPARATOR)
    File.symlink(File.expand_path(dir), target)
  end
end

desc "create vim folders"
task :create_folders do
  Dir.mkdir(@vim_dir)
  Dir.mkdir(@vimswaps)
end

desc "clean up existing folders and links"
task :clean do
  FileUtils.rm_rf Dir[@vim_dir]
  FileUtils.rm_rf Dir[@vimswaps]
  FileUtils.rm @vimrc
end
