" An example for a vimrc file.
"
" Maintainer:	Bram Moolenaar <Bram@vim.org>
" Last change:	2006 Nov 16
"
" To use it, copy it to
"     for Unix and OS/2:  ~/.vimrc
"	      for Amiga:  s:.vimrc
"  for MS-DOS and Win32:  $VIM\_vimrc
"	    for OpenVMS:  sys$login:.vimrc

" When started as "evim", evim.vim will already have done these settings.
if v:progname =~? "evim"
  finish
endif

" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

if has("vms")
  set nobackup		" do not keep a backup file, use versions instead
else
  set backup		" keep a backup file
  set backupdir=~/.vimswaps
  set directory=~/.vimswaps " keep swapfiles in the backup directory
endif

set history=1000	" keep 1000 lines of command line history
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set showmode            " Show current mode at the bottom
set gcr=a:blinkon0      " Disable cursor blink
set incsearch		" do incremental searching
set visualbell          " No sounds
set autoread            " Autoload files changed outside of Vim

" This makes vim act like all other editors, buffers can
" exist in the background without being in a window.
" http://items.sjbach.com/319/configuring-vim-right
set hidden

" For Win32 GUI: remove 't' flag from 'guioptions': no tearoff menu entries
" let &guioptions = substitute(&guioptions, "t", "", "g")

" Don't use Ex mode, use Q for formatting
map Q gq

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
  set mouse=a
endif

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Plugin related settings                                                      "
"                                                                              "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
call pathogen#infect()

" Only do this part when compiled with support for autocommands.
if has("autocmd")

  " Enable file type detection.
  " Use the default filetype settings, so that mail gets 'tw' set to 72,
  " 'cindent' is on in C files, etc.
  " Also load indent files, to automatically do language-dependent indenting.
  filetype on           " Enable filetype detection
  filetype indent on    " Enable filetype-specific indenting
  filetype plugin on    " Enable filetype-specific plugins

  " Put these in an autocmd group, so that we can delete them easily.
  augroup vimrcEx
    autocmd!

    " For all text files set 'textwidth' to 78 characters.
    autocmd FileType text setlocal textwidth=78

    " When editing a file, always jump to the last known cursor position.
    " Don't do it when the position is invalid or when inside an event handler
    " (happens when dropping a file on gvim).
    autocmd BufReadPost *
          \ if line("'\"") > 0 && line("'\"") <= line("$") |
          \   exe "normal! g`\"" |
          \ endif

    " FileType autocommands
    autocmd FileType javascript nnoremap <buffer> <localleader>c I// <esc>
    autocmd FileType c nnoremap <buffer> <localleader>c I// <esc>
    autocmd FileType cpp nnoremap <buffer> <localleader>c I// <esc>
    autocmd FileType python nnoremap <buffer> <localleader>c I# <esc>
    autocmd FileType ruby nnoremap <buffer> <localleader>c I# <esc>

    " Vimscript file settings ----- {{{
    autocmd FileType vim setlocal foldmethod=marker
    " }}}

  augroup END

else

  set cindent		" always set autoindenting on

endif " has("autocmd")

" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
"command DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis | wincmd p | diffthis

" Added by Raj Sahae 2011.09.19
set softtabstop=2	" set tabs to be 2 spaces instead of 8
set shiftwidth=2	" set shiftwidth to be 2 instead of 8
set expandtab		" use spaces to insert a tab
set sm				" search magic on
set guifont=monospace\ 13	" Use monospaced font
set number
set wrap
set ignorecase		" ignore case in a pattern
set smartcase		" Ignore case when pattern is lowercase letters only
"set vb				" Use visual bell instead of beeping
set autoindent		" always set autoindenting on

" Java Highlighting, Syntax, and C++ error marking
"let java_highlight_all=1
"let java_highlight_functions="style"
"let java_highlight_cpp_keywords=1

" Added by Raj Sahae 2011.12.13
"command Rake !rake
"command WR w|!rake

" Added by Raj Sahae 2012.01.03
"compiler ruby         " Enable compiler support for ruby

" Added by Raj Sahae 2012.01.11
"runtime bundles/tplugin_vim/macros/tplugin.vim
"runtime bundles/tskeleton/macros/tskeleton.vim

" Added by Raj Sahae 2012.01.23
set nospell             " Enable spellchecker

" Added by Raj Sahae 2012.02.15
set foldmethod=syntax   " Set foldmethod to fold by indents
set foldlevel=2         " Set initial foldlevel to 2 => Added 2013.01.30

" Added by Raj Sahae 2012.06.10
let mapleader = ","     " Set leader to comma
let maplocalleader = "-" " Set local leader to hyphen
colorscheme ir_black

" Swap the  ' and ` keys
nnoremap ' `
nnoremap ` '

" Single character insert
nnoremap <Leader><Space> i_<Esc>r

runtime macros/matchit.vim    " Enable extended % matching
set wildmenu                  " use the wildmenu for tab completion
set wildmode=list:longest     " shell style completion
set title                     " Set terminal title
set scrolloff=3               " Maintain 3 lines of context around the cursor
" Catch trailing whitespace
set listchars=tab:>-,trail:.,eol:$
nmap <silent> <leader>s :set nolist!<CR>
set shortmess=atI             " Stifle interrupting prompts

" Remap window and buffer commands
nnoremap <leader>c <C-w>c
nnoremap <leader>s <C-w>s<C-w>j
nnoremap <leader>v <C-w>v<C-w>l
nnoremap <leader>w <C-w>w
nnoremap <leader>l <C-w>l
nnoremap <leader>h <C-w>h
nnoremap <leader>k <C-w>k
nnoremap <leader>j <C-w>j
nnoremap <leader>bn :bn<CR>
nnoremap <leader>bp :bp<CR>
nnoremap <leader><leader>w :w<CR>
"inoremap <leader><leader>c <ESC>
" expand current buffer to whole screen
nnoremap <leader>o <c-w><c-_><c-w><bar>
" equal window sizes
nnoremap <leader>= <c-w>=
" open previous buffer to in new buffer on right
nnoremap <leader>p :rightbelow vsplit bufname("#")<cr>
" highlight trailing whitespace
nnoremap <leader>tw :match Error /\v\s+$/<cr>
" delete trailing whitespace
nnoremap <leader>dw ma:%s/\v\s+$//<cr>`a
" clear previous match pattern
nnoremap <leader>mn :match none<cr>
" Mapping for toggling line numbers
nnoremap <leader>n :setlocal number!<cr>

" Remap for Gundo Plugin
nnoremap <F5> :GundoToggle<CR>

" key mappings for pair completion
"inoremap ( ()<Left>
"inoremap { {}<Left>
"inoremap <%= <%=%><Left><Left>
"inoremap <% <%%><Left><Left>
inoremap {<CR> {<CR>}<Esc>O
inoremap do<CR> do<CR>end<Esc>O
inoremap \|<CR> \|<CR>end<Esc>O
"inoremap <expr> )  strpart(getline('.'), col('.')-1, 1) == ")" ? "\<Right>" : ")"
"inoremap <expr> }  strpart(getline('.'), col('.')-1, 1) == "}" ? "\<Right>" : "}"
"inoremap <expr> %>  strpart(getline('.'), col('.')-1, 2) == "%>" ? "\<Right><Right>" : "%>"
"inoremap def<Space> def<CR>end<Esc><Up>A<Space>

" Color everything after column 80 differently
"let &colorcolumn="80,".join(range(120,999),",")
"highlight ColorColumn ctermbg=235 guibg=DarkGrey

" vimrc edit and sourcing shortcuts
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

" Remap jk for escaping from insert and visual mode.
" Disable ESC and CTRL-C for now to relearn
inoremap jk <esc>
"inoremap <leader><leader><leader> <esc>
inoremap <esc> <nop>
inoremap <c-c> <nop>
vnoremap jk <esc>
"vnoremap <leader><leader><leader> <esc>
vnoremap <esc> <nop>
vnoremap <c-c> <nop>


"""" operator mappings
" in next parentheses
onoremap in( :<c-u>normal! f(vi(<cr>
" in last parentheses
onoremap il( :<c-u>normal! F)vi(<cr>
" around next parentheses
onoremap an( :<c-u>normal! f(v%<cr>
" around last parentheses
onoremap al( :<c-u>normal! F(v%<cr>

" in next set of braces
onoremap in{ :<c-u>normal! f{vi{<cr>
" in last set of braces
onoremap il{ :<c-u>normal! F}vi{<cr>
" around next set of braces
onoremap an{ :<c-u>normal! f{v%<cr>
" around last set of braces
onoremap al{ :<c-u>normal! F{v%<cr>

" c++ edit shortcuts
nnoremap <leader>ss :e %:p:s,.h$,.X123X,:s,.cpp$,.h,:s,.X123X$,.cpp,<CR>
