@local_zshrc   = File.expand_path("zshrc")
@local_aliases = File.expand_path("aliases")
@zshrc         = File.expand_path("~/.zshrc")
@aliases       = File.expand_path("~/.aliases")

desc "install links to home dir"
task :install do
  File.symlink(@local_zshrc, @zshrc)
  File.symlink(@local_aliases, @aliases)
end

desc "clean up existing folders and links"
task :clean do
  FileUtils.rm @zshrc
  FileUtils.rm @aliases
end
